version: 0.2

env:
    variables:
        S3_BUCKET: "gaberatcliff.com"
        BUILD_ENV : "prod"
        BUILD_DIR : "dist"

phases:
    install:
        commands:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - echo Installing nodeJs
        - sudo apt-get update -y
        - sudo apt-get install -y nodejs
        - sudo apt-get install -y apt-transport-https
        - npm install

    build:
        commands:
        - echo Build started
        - npm run build

    post_build:
        commands:
        - aws s3 rm s3://${S3_BUCKET} --recursive
        - echo S3 bucket is cleared
        - aws s3 cp ${BUILD_DIR}/* s3://${S3_BUCKET} --acl public-read --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'
